// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4kHMsOlrsy343dbd0w2c6QuYmO4xQiw',
    appId: '1:426558435758:web:4344192f96fdd55568183f',
    messagingSenderId: '426558435758',
    projectId: 'flugo-desafio',
    authDomain: 'flugo-desafio.firebaseapp.com',
    databaseURL: 'https://flugo-desafio-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-desafio.firebasestorage.app',
    measurementId: 'G-SK8LXE85MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLclmW4kCmLDfocWLW05szmylC3ejB_is',
    appId: '1:426558435758:android:09a3724c4573a01f68183f',
    messagingSenderId: '426558435758',
    projectId: 'flugo-desafio',
    databaseURL: 'https://flugo-desafio-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-desafio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJEplz8GuJ27U6abfYe5YooScgd2LMr1g',
    appId: '1:426558435758:ios:3ccbdd140180ec6468183f',
    messagingSenderId: '426558435758',
    projectId: 'flugo-desafio',
    databaseURL: 'https://flugo-desafio-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-desafio.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJEplz8GuJ27U6abfYe5YooScgd2LMr1g',
    appId: '1:426558435758:ios:3ccbdd140180ec6468183f',
    messagingSenderId: '426558435758',
    projectId: 'flugo-desafio',
    databaseURL: 'https://flugo-desafio-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-desafio.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4kHMsOlrsy343dbd0w2c6QuYmO4xQiw',
    appId: '1:426558435758:web:695b0b29919e40ab68183f',
    messagingSenderId: '426558435758',
    projectId: 'flugo-desafio',
    authDomain: 'flugo-desafio.firebaseapp.com',
    databaseURL: 'https://flugo-desafio-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-desafio.firebasestorage.app',
    measurementId: 'G-TSD1JWP5R8',
  );
}
