// Mocks generated by Mockito 5.4.6 from annotations
// in chat_app_firebase/test/viewmodels/conversation_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chat_app_firebase/models/chat_model.dart' as _i5;
import 'package:chat_app_firebase/models/message_model.dart' as _i6;
import 'package:chat_app_firebase/models/user_model.dart' as _i7;
import 'package:chat_app_firebase/services/auth_service.dart' as _i8;
import 'package:chat_app_firebase/services/conversation_service.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConversationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationService extends _i1.Mock
    implements _i2.ConversationService {
  @override
  _i3.Future<String> getOrCreateChat(
    String? userId1,
    String? userId2,
    String? userName1,
    String? userName2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateChat, [
              userId1,
              userId2,
              userName1,
              userName2,
            ]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateChat, [
                  userId1,
                  userId2,
                  userName1,
                  userName2,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateChat, [
                  userId1,
                  userId2,
                  userName1,
                  userName2,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<List<_i5.ChatModel>> getUserChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChats, [userId]),
            returnValue: _i3.Stream<List<_i5.ChatModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i5.ChatModel>>.empty(),
          )
          as _i3.Stream<List<_i5.ChatModel>>);

  @override
  _i3.Stream<List<_i6.MessageModel>> getChatMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [chatId]),
            returnValue: _i3.Stream<List<_i6.MessageModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i6.MessageModel>>.empty(),
          )
          as _i3.Stream<List<_i6.MessageModel>>);

  @override
  _i3.Future<void> sendMessage({
    required String? chatId,
    required String? text,
    required String? senderName,
    required String? senderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatId: chatId,
              #text: text,
              #senderName: senderName,
              #senderId: senderId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markMessagesAsRead(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [chatId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setTypingStatus(
    String? chatId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [chatId, userId, isTyping]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i7.UserModel>> getAvailableUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableUsers, []),
            returnValue: _i3.Stream<List<_i7.UserModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i7.UserModel>>.empty(),
          )
          as _i3.Stream<List<_i7.UserModel>>);

  @override
  _i3.Future<void> updateUserPresence(_i7.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPresence, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserFCMToken(String? userId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserFCMToken, [userId, token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserFCMToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFCMToken, [userId]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  _i3.Stream<_i9.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i9.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i9.User?>.empty(),
          )
          as _i3.Stream<_i9.User?>);

  @override
  _i3.Future<_i7.UserModel?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i7.UserModel?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.UserModel?>.value(),
          )
          as _i3.Future<_i7.UserModel?>);

  @override
  _i3.Future<_i7.UserModel?> registerWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i3.Future<_i7.UserModel?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.UserModel?>.value(),
          )
          as _i3.Future<_i7.UserModel?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
